### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by jacobtomlinson** [opsdroid/database-redis#2]
This is awesome. You're officially the first person (that I know of) to create a third party library for opsdroid.

I've tested it and with the addition of #1 it works perfectly for me.

I'm keen to add this to the official list of opsdroid skills. I can either fork it to the opsdroid org but that requires syncing changes, or you can change the ownership to the opsdroid org and I can ensure you remain as the maintainer with full control over it.

What do you think?

**Comment by arhix** [comment]
Hi Jacob, thanks you.
I will change the ownership to the opsdroid org.

**Comment by arhix** [comment]
I can't pass the repository to opsdroid org. Can you help me with it?

**Comment by jacobtomlinson** [comment]
Sure. You should be able to go to the repo, go to settings and click the "transfer ownership" button at the bottom. Then type the name of the repo and then the name of the opsdroid org.

![image](https://user-images.githubusercontent.com/1610850/29510255-0cbc3d50-8653-11e7-8780-f78043cc4324.png)

**Comment by arhix** [comment]
I got an error
![2017-08-21 10 30 39](https://user-images.githubusercontent.com/5672013/29510368-d3ece2aa-865b-11e7-8810-1d3c7013e86c.png)

**Comment by jacobtomlinson** [comment]
Try adding me as a collaborator with admin privs and I might be able to move it.

**Comment by jacobtomlinson** [comment]
That didn't work. I've added you to opsdroid so try transferring it again.

**Comment by arhix** [comment]
Done. Thanks for your help

**Comment by jacobtomlinson** [comment]
Thanks for moving this over, it's awesome! You should see it is now listed on https://opsdroid.github.io/.

You should also see you are still a contributor on the repo so you have full control to merge PRs and update it.
